version: '3'
services:
  reflector:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
# environment:
#   - CONSUMER_TOPICS=
#   - CONSUMER_SERVER=
#   - CONSUMER_GROUP_ID=
#   - PRODUCER_TOPIC=
#   - PRODUCER_SERVER=
#   - METRICS_HOST=
#   - METRICS_TOPIC=

